# # Use postgres/example user/password credentials
version: "3.1"
name: dicoding_belajar_fundamental_aplikasi_backend_dicoding
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: M@ntap23
      POSTGRES_USER: sarewes23
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
# version: '3.5'

# volumes:
#   local_postgres_data: {}

# services:
#   postgres:
#     build: ./
#     image: postgres:latest
#     container_name: localpostgres
#     environment:
#       POSTGRES_USER: "sarewes23"
#       POSTGRES_PASSWORD: "M@ntap23"
#       POSTGRES_PORT: "5432"
#     volumes:
#       - local_postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
